/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
 module.exports = {
  contentSidebar: [
    'intro',
    {
      type: 'category',
      label: 'IOTA',
      items: [{
        type: 'autogenerated',
        dirName: 'section-1'
      }]
    },
    {
      type: 'category',
      label: 'TLIP Infrastructure',
      items: [{
        type: 'autogenerated',
        dirName: 'section-2'
      }]
    },
    {
      type: 'category',
      label: 'FAQs',
      items: [{
        type: 'autogenerated',
        dirName: 'section-3'
      }]
    },
    {
      type: 'category',
      label: 'TLIP Development',
      items: [{
        type: 'autogenerated',
        dirName: 'section-4'
      }]
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [{
        type: 'autogenerated',
        dirName: 'section-5'
      }]
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [{
        type: 'autogenerated',
        dirName: 'section-6'
      }]
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        'section-7/overview',   // Main topic (Integration overview)
        
        {
          type: 'category',
          label: 'The Bridge ',
          items: [
            'section-7/subtopic-1/overview',  // Subtopic 1 overview
            'section-7/subtopic-1/sub-subtopic-1',  // Ensure this file exists
            'section-7/subtopic-1/sub-subtopic-2',  // Ensure this file exists
            'section-7/subtopic-1/sub-subtopic-3',  // Ensure this file exists
          ],
        },
       
        {
          type: 'category',
          label: 'TLIP Connector',
          items: [
            'section-7/subtopic-2/overview',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-1',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-2',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-3',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-4',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-5',  // Ensure this file exists
            'section-7/subtopic-2/sub-subtopic-6',  // Ensure this file exists
          ],
        },
      ],
    },
  ],
};

