name: docs.tlip.io Build and Deploy

on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/docs.yaml"
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: docs

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.DOCS_VERCEL_PROJECT_ID }}
      VERCEL_PROJECT_NAME: ${{ secrets.DOCS_VERCEL_PROJECT_NAME }}
      VERCEL_DOMAIN: ${{ secrets.DOCS_DOMAIN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
      - name: Build
        run: |
          npm install
          npm run deploy-build
          cd build
      - name: Deploy
        run: |
          VERCEL_DEPLOYMENT_URL=$(npx vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_SCOPE }} --force -m githubCommitSha=${{ github.sha }} | sed 's,https://,,g')
          npx vercel alias set --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_SCOPE }} $VERCEL_DEPLOYMENT_URL $VERCEL_DOMAIN
